applications:
  learning_logs:
    type: python:3.13
    source:
      root: "Llogs"   # folder containing manage.py
    # dependencies:
    #   python3:
    #     Django: ">=4.2,<5.0"
    #     gunicorn: "*"
    #     psycopg2-binary: "*"
    web:                            #"gunicorn -b unix:$SOCKET ll_project.wsgi:application"
      commands:
        start: "gunicorn -b unix:$SOCKET ll_project.wsgi:application"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
        "/static":
          allow: true
          expires: "1h"
          root: "staticfiles"
    hooks:
      build: |
        set -eux
        pip install --upgrade pip
        pip install -r requirements.txt
         
        
      deploy: |
        set -eux
        python manage.py collectstatic --noinput
        python manage.py migrate
    relationships:
      database: postgresql:postgresql  # ✅ just the service name
    
    mounts:
      "/staticfiles":
        source: "local"
        source_path: "static_assets"

services:
  postgresql:
    type: postgresql:18   # service name matches relationship

routes:
  "https://{default}/":
    type: upstream
    upstream: "learning_logs:http"
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"