applications:
  learning_logs:
    type: python:3.13
    source:
      root: "Llogs"   # folder containing manage.py
    web:
      commands:
        start: "gunicorn --pythonpath=. -b unix:$SOCKET Llogs.wsgi --log-file -"
      upstream:
        socket_family: unix
      locations:
        "/":
          passthru: true
        "/static":
          allow: true
          expires: "1h"
          root: "static"
    hooks:
      build: |
        set -eux
        python manage.py collectstatic --noinput
      deploy: |
        set -eux
        python manage.py migrate

services:
  postgresql:
    type: postgresql:18

routes:
  "https://{default}/":
    type: upstream
    upstream: "learning_logs:http"
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"