"""
Django settings for ll_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import json
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q*fol4@#ue1zfga010y0dbim3zvgo89w)iqi9ilp4to$r=6y%^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #My apps
    'learning_logs',
    'accounts',

    'django_bootstrap5',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'll_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'll_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Production/Upsun settings.
if (os.getenv('PLATFORM_APPLICATION_NAME') is not None):
    DEBUG = False

    # Static dir.
    if (os.getenv('PLATFORM_APP_DIR') is not None):
        STATIC_ROOT = os.path.join(os.getenv('PLATFORM_APP_DIR'), 'static')

    # Secret Key.
    if (os.getenv('PLATFORM_PROJECT_ENTROPY') is not None):
        SECRET_KEY = os.getenv('PLATFORM_PROJECT_ENTROPY')

    # Production database configuration.
   
    platform_relationships = os.getenv("PLATFORM_RELATIONSHIPS")

    if platform_relationships and platform_relationships.strip():
        try:
            relationships = json.loads(platform_relationships)
            
            # find postgres relationship dynamically
            for rel in relationships.values():
                if rel and rel[0].get("scheme") == "postgresql":
                    postgres = rel[0]
                    
                    DATABASES["default"] = {
                        "ENGINE": "django.db.backends.postgresql",
                        "NAME": postgres["path"],
                        "USER": postgres["username"],
                        "PASSWORD": postgres["password"],
                        "HOST": postgres["host"],
                        "PORT": postgres["port"],
                    }
                    break
        except (json.JSONDecodeError, KeyError, IndexError) as e:
            # If anything goes wrong with PostgreSQL config, stick with SQLite
            print(f"Warning: Could not configure PostgreSQL database: {e}")
            pass
    # if os.getenv("PLATFORM_RELATIONSHIPS"):
    #     platform_relationships = os.getenv("PLATFORM_RELATIONSHIPS")

    #     try:
    #         relationships = json.loads(platform_relationships) if platform_relationships.strip() else {}
    #     except json.JSONDecodeError:
    #         relationships = {}

    #     postgres = None

    #     if relationships:
    #         # get first available relationship automatically
    #         postgres = list(relationships.values())[0][0]

    #     DATABASE_URL = (
    #         f"postgresql://{postgres['username']}:{postgres['password']}"
    #         f"@{postgres['host']}:{postgres['port']}/{postgres['path']}"
    #     )

    #     DATABASES = {
    #         "default": dj_database_url.parse(
    #             DATABASE_URL,
    #             conn_max_age=600,
    #         )
    #     }


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
LOGIN_REDIRECT_URL = 'learning_logs:index'
LOGOUT_REDIRECT_URL = 'learning_logs:index'
LOGIN_URL = 'accounts:login'